export const AndroidCallState = Object.freeze({
  PJSIP_INV_STATE_NULL: 0,
  PJSIP_INV_STATE_CALLING: 1,
  PJSIP_INV_STATE_INCOMING: 2,
  PJSIP_INV_STATE_EARLY: 3,
  PJSIP_INV_STATE_CONNECTING: 4,
  PJSIP_INV_STATE_CONFIRMED: 5,
  PJSIP_INV_STATE_DISCONNECTED: 6,
});
